org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dkotlin.daemon.jvm.options=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=false
android.disableResourceValidation=true

